infolugares=[["Baleares","../imgs/imgLugar/baleares/balearesBanner.jpg",
        ,"../imgs/imgLugar/baleares/baleares(archipielagocabrera).jpg",
        ,"../imgs/imgLugar/baleares/baleares(formentera).jpg",
        ,"../imgs/imgLugar/baleares/baleares(ibiza).jpg",
        ,"../imgs/imgLugar/baleares/baleares(mallorca).jpg",
        ,"../imgs/imgLugar/baleares/baleares(menorca).jpg"],
            


["Barcelona","../imgs/imgLugar/barcelona/barcelonaBanner.jpg","../imgs/imgLugar/barcelona/barcelona(batllo).jpg","../imgs/imgLugar/barcelona/barcelona(campnou).jpg","../imgs/imgLugar/barcelona/barcelona(catedral).jpg","../imgs/imgLugar/barcelona/barcelona(lapedrera).jpg","../imgs/imgLugar/barcelona/barcelona(liceu).jpg","../imgs/imgLugar/barcelona/barcelona(macba).jpg","../imgs/imgLugar/barcelona/barcelona(mnac).jpg","../imgs/imgLugar/barcelona/barcelona(palaumusica).jpg","../imgs/imgLugar/barcelona/barcelona(picasso).jpg","../imgs/imgLugar/barcelona/barcelona(sagradafamilia).jpg"],
            ["Bilbao","../imgs/imgLugar/bilbao/bilbaoBanner.jpg","../imgs/imgLugar/bilbao/bilbao(arriaga).jpg","../imgs/imgLugar/bilbao/bilbao(ayuntamiento).jpg","../imgs/imgLugar/bilbao/bilbao(basilicabegoña).jpg","../imgs/imgLugar/bilbao/bilbao(belasartesbilbao).jpg","../imgs/imgLugar/bilbao/bilbao(catedralsantiago).jpg","../imgs/imgLugar/bilbao/bilbao(diputacion).jpg","../imgs/imgLugar/bilbao/bilbao(guggenheim).jpg","../imgs/imgLugar/bilbao/bilbao(plazanueva).jpg","../imgs/imgLugar/bilbao/bilbao(ribera).jpg","../imgs/imgLugar/bilbao/bilbao(universidaddeusto).jpg"],
            ["Canarias","../imgs/imgLugar/canarias/canarias1Banner.jpg","../imgs/imgLugar/canarias/canarias(elhierro).jpg","../imgs/imgLugar/canarias/canarias(fuerteventura).jpg","../imgs/imgLugar/canarias/canarias(grancanaria).jpg","../imgs/imgLugar/canarias/canarias(lagomera).jpg","../imgs/imgLugar/canarias/canarias(lagraciosa).jpg","../imgs/imgLugar/canarias/canarias(lanzarote).jpg","../imgs/imgLugar/canarias/canarias(lapalma).jpg","../imgs/imgLugar/canarias/canarias(tenerife).jpg"],
            ["Madrid","../imgs/imgLugar/madrid/madrid1Banner.jpg","../imgs/imgLugar/madrid/madird(palacioreal).jpg","../imgs/imgLugar/madrid/madrid(alcala).jpg","../imgs/imgLugar/madrid/madrid(buenretiro).jpg","../imgs/imgLugar/madrid/madrid(cisneros).jpg","../imgs/imgLugar/madrid/madrid(plazaMayor).jpg","../imgs/imgLugar/madrid/madrid(Prado).jpg","../imgs/imgLugar/madrid/madrid(ReinaSofia).jpg","../imgs/imgLugar/madrid/madrid(thyssenBornemisza).jpg"],
            ["Malaga","../imgs/imgLugar/malaga/malagaBanner.jpg","../imgs/imgLugar/malaga/malaga(alcazaba).jpg","../imgs/imgLugar/malaga/malaga(barriodelasartes).jpg","../imgs/imgLugar/malaga/malaga(catedral).jpg","../imgs/imgLugar/malaga/malaga(museoRuso).jpg","../imgs/imgLugar/malaga/malaga(parquedemalaga).jpg","../imgs/imgLugar/malaga/malaga(picaso).jpg","../imgs/imgLugar/malaga/malaga(pompidou).jpg","../imgs/imgLugar/malaga/malaga(teatroRomano).jpg","../imgs/imgLugar/malaga/malaga(thyssen).jpg"],
            ["Santander","../imgs/imgLugar/santander/santander1Banner.jpg","../imgs/imgLugar/santander/santander(asuncion).jpg","../imgs/imgLugar/santander/santander(centrobotin).jpg","../imgs/imgLugar/santander/santander(elcamello).jpg","../imgs/imgLugar/santander/santander(laconcha).jpg","../imgs/imgLugar/santander/santander(lospeligros).jpg","../imgs/imgLugar/santander/santander(mataleñas).jpg","../imgs/imgLugar/santander/santander(museomaritimodelcantabico).jpg","../imgs/imgLugar/santander/santander(museoprehistoria).jpg","../imgs/imgLugar/santander/santander(sardinero1).jpg","../imgs/imgLugar/santander/santander(sardinero2).jpg"],
            ["Santiago de Compostela","../imgs/imgLugar/santiagodeCompostela/santiagodeCompostela1Banner.jpg","../imgs/imgLugar/santiagodeCompostela/santiagodeCompostela(cabildo).jpg","../imgs/imgLugar/santiagodeCompostela/santiagodeCompostela(catedraldecopostela).jpg","../imgs/imgLugar/santiagodeCompostela/santiagodeCompostela(cgac).jpg","../imgs/imgLugar/santiagodeCompostela/santiagodeCompostela(museodelacatedral).jpg","../imgs/imgLugar/santiagodeCompostela/santiagodeCompostela(museodelpueblogallego).jpg","../imgs/imgLugar/santiagodeCompostela/santiagodeCompostela(raxoi).jpg","../imgs/imgLugar/santiagodeCompostela/santiagodeCompostela(reyescatolicos).jpg","../imgs/imgLugar/santiagodeCompostela/santiagodeCompostela(trasouto).jpg"],
            ["Sevilla","../imgs/imgLugar/sevilla/sevilla1Banner.jpg","../imgs/imgLugar/sevilla/sevilla(alcazarSevilla).jpg","../imgs/imgLugar/sevilla/sevilla(america).jpg","../imgs/imgLugar/sevilla/sevilla(ayuntamiento).jpg","../imgs/imgLugar/sevilla/sevilla(catedral).jpg","../imgs/imgLugar/sevilla/sevilla(giralda).jpg","../imgs/imgLugar/sevilla/sevilla(indias).jpg","../imgs/imgLugar/sevilla/sevilla(murillo).jpg","../imgs/imgLugar/sevilla/sevilla(oro).jpg","../imgs/imgLugar/sevilla/sevilla(santacruz).jpg","../imgs/imgLugar/sevilla/sevilla(setas).jpg"],
            ["valencia","../imgs/imgLugar/valencia/valencia1Banner.jpg","../imgs/imgLugar/valencia/valencia(artes y ciencias).jpg","../imgs/imgLugar/valencia/valencia(catedral).jpg","../imgs/imgLugar/valencia/valencia(ciencias).jpg","../imgs/imgLugar/valencia/valencia(generalitat).jpg","../imgs/imgLugar/valencia/valencia(ivam).jpg","../imgs/imgLugar/valencia/valencia(mighelete).jpg","../imgs/imgLugar/valencia/valencia(musica).jpg","../imgs/imgLugar/valencia/valencia(seda).jpg"],
            ["Zaragoza","../imgs/imgLugar/zaragoza/zaragozaBanner.jpg","../imgs/imgLugar/zaragoza/zaragoza(acuario).jpg","../imgs/imgLugar/zaragoza/zaragoza(aljaferia).jpg","../imgs/imgLugar/zaragoza/zaragoza(caesaraugusta).jpg","../imgs/imgLugar/zaragoza/zaragoza(lonja).jpg","../imgs/imgLugar/zaragoza/zaragoza(nuestraseñoradelpilar).jpg","../imgs/imgLugar/zaragoza/zaragoza(pabloserrano).jpg","../imgs/imgLugar/zaragoza/zaragoza(salvador).jpg","../imgs/imgLugar/zaragoza/zaragoza(sanpablo).jpg","../imgs/imgLugar/zaragoza/zaragoza(santaengracia).jpg","../imgs/imgLugar/zaragoza/zaragoza(tercermilenio).jpg"]]

Text="Lorem ipsum dolor, sit amet consectetur adipisicing elit. Atque ipsa mollitia libero illo impedit laboriosam alias provident. Consequatur earum, provident soluta veniam nobis, quos, iusto sit nihil accusantium tempore quaerat."